services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=/api
    container_name: finmech-web
    ports:
      - "3000:3000"
    environment:
      - API_INTERNAL_URL=${API_INTERNAL_URL:-http://finmech-api:5000}
    networks:
      - finmech-net
    restart: unless-stopped

networks:
  finmech-net:
    external: true
    name: finmech-net
