import type { CalculationExport } from "@/lib/calculation-pdf";
import { formatCurrency } from "@/lib/utils";
import { QUESTIONS, type ChecklistResponse } from "@/lib/checklist-model";

function fmt(v: unknown): string {
  if (v === null || v === undefined) return "—";
  if (typeof v === "number") {
    if (!Number.isFinite(v)) return "—";
    if (Math.abs(v) >= 1000) return formatCurrency(v);
    if (v % 1 !== 0) return v.toFixed(2);
    return v.toLocaleString();
  }
  return String(v);
}

function pct(n: number, d: number): string {
  if (!d) return "0%";
  return `${((n / d) * 100).toFixed(1)}%`;
}

export const FREE_MODEL_SLUGS = new Set([
  "revenue-model",
  "costing-model",
  "break-even-pro",
  "break-even-basic",
  "know-your-numbers",
]);

type Row = { label: string; value: string };

// ── HTML building blocks ──────────────────────────────────────────────────────

function p(txt: string) {
  return `<p style="margin:8px 0;font-size:12px;color:#333;line-height:1.7">${txt}</p>`;
}

function bullet(txt: string) {
  return `<li style="font-size:12px;color:#333;line-height:1.8;margin-bottom:6px">${txt}</li>`;
}

function section(title: string, body: string) {
  return `<div style="margin-top:20px">
    <h4 style="font-size:11px;font-weight:800;color:#6d28d9;text-transform:uppercase;letter-spacing:1.2px;margin:0 0 10px;border-bottom:2px solid #e9e0ff;padding-bottom:6px">${title}</h4>
    ${body}
  </div>`;
}

function callout(type: "info" | "warn" | "ok" | "risk", title: string, body: string) {
  const styles = {
    info: { bg: "#eff6ff", border: "#3b82f6", color: "#1d4ed8" },
    warn: { bg: "#fffbeb", border: "#f59e0b", color: "#b45309" },
    ok: { bg: "#f0fdf4", border: "#22c55e", color: "#15803d" },
    risk: { bg: "#fef2f2", border: "#ef4444", color: "#b91c1c" },
  }[type];
  return `<div style="margin:10px 0;padding:12px 14px;background:${styles.bg};border-left:4px solid ${styles.border};border-radius:0 6px 6px 0">
    <div style="font-size:11px;font-weight:800;color:${styles.color};margin-bottom:4px">${title}</div>
    <div style="font-size:12px;color:#444;line-height:1.65">${body}</div>
  </div>`;
}

function metricTable(rows: { label: string; value: string; note?: string }[], accent = "#6d28d9") {
  return `<table style="width:100%;border-collapse:collapse;font-size:12px;margin:8px 0">
    ${rows.map((r, i) => `<tr style="background:${i % 2 === 0 ? "#fafafa" : "#fff"}">
      <td style="padding:8px 12px;border-bottom:1px solid #eee;color:#555;width:42%">${r.label}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #eee;text-align:right;font-weight:700;color:${accent}">${r.value}</td>
      ${r.note ? `<td style="padding:8px 12px;border-bottom:1px solid #eee;color:#888;font-size:11px">${r.note}</td>` : ""}
    </tr>`).join("")}
  </table>`;
}

function numberedPlan(title: string, items: string[]) {
  return `<div style="margin-top:8px"><strong style="font-size:12px;color:#444">${title}</strong>
    <ol style="margin:8px 0 0 20px;padding:0">${items.map((t) => `<li style="font-size:12px;color:#333;line-height:1.75;margin-bottom:6px">${t}</li>`).join("")}</ol></div>`;
}

function scenarioTable(headers: string[], rows: string[][]) {
  return `<table style="width:100%;border-collapse:collapse;font-size:11px;margin:10px 0">
    <thead><tr style="background:#6d28d9;color:#fff">${headers.map((h) => `<th style="padding:8px 10px;text-align:${h === headers[0] ? "left" : "right"}">${h}</th>`).join("")}</tr></thead>
    <tbody>${rows.map((row, i) => `<tr style="background:${i % 2 === 0 ? "#fafafa" : "#fff"}">${row.map((cell, j) => `<td style="padding:7px 10px;border-bottom:1px solid #eee;text-align:${j === 0 ? "left" : "right"};${j > 0 ? "font-weight:600" : ""}">${cell}</td>`).join("")}</tr>`).join("")}</tbody>
  </table>`;
}

function wrapAnalysis(sections: string) {
  return `<div style="margin-top:28px;padding:22px 26px;background:linear-gradient(135deg,#f8f9ff 0%,#fff 60%);border:1px solid #e9e0ff;border-left:5px solid #6d28d9;border-radius:0 10px 10px 0">
    <div style="display:flex;align-items:center;gap:10px;margin-bottom:6px">
      <span style="font-size:20px">✦</span>
      <h3 style="margin:0;font-size:14px;color:#6d28d9;text-transform:uppercase;letter-spacing:1.2px;font-weight:800">Smart Results — Full Advisory Report</h3>
    </div>
    <p style="margin:0 0 16px;font-size:11px;color:#888;line-height:1.5">Founder-grade analysis: every metric explained, benchmarked, stress-tested, and translated into a concrete improvement roadmap.</p>
    ${sections}
    <div style="margin-top:20px;padding-top:12px;border-top:1px dashed #ddd;font-size:10px;color:#aaa;text-align:center">Generated by FinMech Smart Results · For internal planning &amp; investor discussions</div>
  </div>`;
}

// ── REVENUE MODEL ─────────────────────────────────────────────────────────────

function analyzeRevenue(out: Record<string, unknown>, inp: Record<string, unknown>): string {
  const price = Number(out.pricePerUnit) || Number(inp.pricePerUnit) || 0;
  const customers = Number(inp.customersPerMonth) || 0;
  const unitsPerCustomer = Number(inp.unitsPerCustomer) || 0;
  const freq = Number(inp.purchaseFrequencyPerYear) || 0;
  const lifetime = Number(out.customerLifetimeMonths) || Number(inp.customerLifetimeMonths) || 0;
  const monthlyUnits = Number(out.monthlyUnitsSold) || 0;
  const monthly = Number(out.monthlyRevenue) || 0;
  const annual = Number(out.annualRevenue) || monthly * 12;
  const monthlyRate = Number(out.monthlyPurchaseRate) || freq / 12;
  const arpu = customers > 0 ? monthly / customers : 0;
  const revPerUnit = monthlyUnits > 0 ? monthly / monthlyUnits : price;
  const ltvPerCustomer = price * monthlyRate * lifetime;
  const ltvTotal = ltvPerCustomer * customers;
  const annualUnits = monthlyUnits * 12;
  const quarterly = monthly * 3;

  const stage = annual >= 1_000_000 ? "Scale-up" : annual >= 250_000 ? "Growth" : annual >= 50_000 ? "Early traction" : monthly > 0 ? "Pre-revenue / seed" : "Not yet calculated";

  const execSummary = p(`<strong>Executive summary:</strong> Your business generates <strong>${fmt(monthly)}</strong>/month (${fmt(annual)} annual run-rate) by selling <strong>${monthlyUnits.toLocaleString()} units</strong> to <strong>${customers.toLocaleString()} customers</strong> at <strong>${fmt(price)}</strong>/unit. Stage: <strong>${stage}</strong>. Each customer is worth approximately <strong>${fmt(ltvPerCustomer)}</strong> over ${lifetime} months, giving you a monthly LTV pool of <strong>${fmt(ltvTotal)}</strong> across your active customer base.`);

  const resultsTable = metricTable([
    { label: "Price Per Unit", value: fmt(price), note: "Core pricing lever" },
    { label: "Customers Per Month", value: customers.toLocaleString(), note: "Acquisition volume" },
    { label: "Units Per Customer", value: String(unitsPerCustomer), note: "Basket size / upsell" },
    { label: "Purchase Frequency / Year", value: `${freq}x`, note: `${monthlyRate.toFixed(2)}/mo per customer` },
    { label: "Customer Lifetime", value: `${lifetime} months`, note: "Retention horizon" },
    { label: "Monthly Units Sold", value: monthlyUnits.toLocaleString(), note: "Volume driver" },
    { label: "Monthly Revenue", value: fmt(monthly), note: "Primary KPI" },
    { label: "Quarterly Revenue (est.)", value: fmt(quarterly), note: "3× monthly" },
    { label: "Annual Revenue Run-Rate", value: fmt(annual), note: "12× monthly" },
    { label: "Annual Units (est.)", value: annualUnits.toLocaleString(), note: "Capacity planning" },
    { label: "ARPU (Revenue / Customer)", value: fmt(arpu), note: "Monetisation depth" },
    { label: "Revenue Per Unit Sold", value: fmt(revPerUnit), note: "Effective realisation" },
    { label: "LTV Per Customer", value: fmt(ltvPerCustomer), note: "Max affordable CAC reference" },
    { label: "Total Monthly LTV Pool", value: fmt(ltvTotal), note: "All customers combined" },
  ]);

  let deepDive = p(`<strong>Monthly revenue mechanics:</strong> Revenue = Customers (${customers}) × Units/Customer (${unitsPerCustomer}) × Price (${fmt(price)}) = <strong>${fmt(monthly)}</strong>. This is a ${unitsPerCustomer > 1 ? "multi-unit" : "single-unit"} purchase model with ${freq >= 12 ? "high" : freq >= 4 ? "moderate" : "low"} purchase frequency (${freq}x/year).`);

  deepDive += p(`<strong>Customer lifetime value:</strong> LTV = Price (${fmt(price)}) × Monthly purchase rate (${monthlyRate.toFixed(2)}) × Lifetime (${lifetime} mo) = <strong>${fmt(ltvPerCustomer)}</strong>. Rule of thumb: your Customer Acquisition Cost (CAC) should stay below ${fmt(ltvPerCustomer / 3)} (⅓ of LTV) for healthy unit economics, and below ${fmt(ltvPerCustomer)} absolute maximum.`);

  if (lifetime < 6) deepDive += callout("risk", "Critical — Very Short Lifetime", `At ${lifetime} months, customers leave quickly. Churn is destroying LTV. Implement onboarding sequences, NPS tracking, and exit interviews immediately.`);
  else if (lifetime < 12) deepDive += callout("warn", "Retention Needs Work", `${lifetime}-month lifetime limits LTV to ${fmt(ltvPerCustomer)}. Extending to 18 months would increase LTV by ${fmt(ltvPerCustomer * 0.5)} (+50%).`);
  else deepDive += callout("ok", "Healthy Retention Signal", `${lifetime}-month lifetime supports sustainable growth. Protect with customer success and proactive renewal outreach.`);

  if (freq < 4) deepDive += callout("warn", "Low Purchase Frequency", `Customers buy only ${freq}x/year. Subscription, retainer, or consumable models can 2–3× frequency without new customer acquisition.`);
  if (annual >= 1_000_000) deepDive += callout("ok", "Scale-Up Revenue", `${fmt(annual)} ARR puts you in scale-up territory. Shift focus to gross margin, CAC efficiency, and retention cohort analysis.`);

  const scenarios = scenarioTable(
    ["Scenario", "Monthly Rev", "Annual Rev", "LTV/Customer", "Impact"],
    [
      ["Current (Base)", fmt(monthly), fmt(annual), fmt(ltvPerCustomer), "Baseline"],
      ["+10% Price", fmt(monthly * 1.1), fmt(annual * 1.1), fmt(ltvPerCustomer * 1.1), `+${fmt(monthly * 0.1)}/mo`],
      ["+20% Customers", fmt(monthly * 1.2), fmt(annual * 1.2), fmt(ltvPerCustomer), `+${fmt(monthly * 0.2)}/mo`],
      ["+3 Mo Lifetime", fmt(monthly), fmt(annual), fmt(price * monthlyRate * (lifetime + 3)), `LTV +${fmt(price * monthlyRate * 3)}`],
      ["+1 Unit/Customer", fmt((customers * (unitsPerCustomer + 1)) * price), fmt((customers * (unitsPerCustomer + 1)) * price * 12), fmt(ltvPerCustomer), `Volume uplift`],
      ["Price +10% & +20% Customers", fmt(monthly * 1.1 * 1.2), fmt(annual * 1.32), fmt(ltvPerCustomer * 1.1), `+${fmt(monthly * 0.32)}/mo`],
    ]
  );

  const risks: string[] = [];
  if (customers < 10 && monthly > 0) risks.push("Very small customer base — revenue is fragile; one churned customer materially impacts monthly numbers.");
  if (price === 0) risks.push("Price is zero — model cannot produce meaningful revenue projections.");
  if (ltvPerCustomer < 1000 && monthly > 0) risks.push("Low LTV limits paid acquisition — organic/referral channels may be your only viable growth lever until LTV rises.");
  if (freq === 0) risks.push("Zero purchase frequency — customers are one-time buyers; no recurring revenue engine exists.");
  if (annual > 0 && customers > 0 && arpu < price) risks.push("ARPU below price per unit — customers may be buying fewer units than expected; investigate downgrades or partial purchases.");

  const plan30 = [
    "Document your top 3 customer acquisition channels and cost per customer acquired (CAC) for each.",
    "Run a cohort analysis: of customers acquired 3/6/12 months ago, how many are still active?",
    `Set a target: increase monthly revenue from ${fmt(monthly)} to ${fmt(monthly * 1.15)} within 30 days via price test OR volume push.`,
    "Link to Costing Model — confirm price covers variable + allocated fixed cost per unit.",
    "Link to Break-Even Model — verify current volume exceeds break-even threshold.",
  ];
  const plan60 = [
    "Launch one retention initiative: onboarding email sequence, loyalty discount, or subscription tier.",
    "Segment customers by units/customer — identify upsell candidates buying below average basket size.",
    "Build a simple 12-month revenue forecast using base / +20% / -20% customer growth scenarios.",
    `Benchmark ARPU (${fmt(arpu)}) against 2–3 competitors or industry reports.`,
  ];
  const plan90 = [
    "Establish monthly revenue review cadence: track customers, units, price, and churn.",
    "If LTV/CAC is below 3×, fix acquisition or retention before scaling ad spend.",
    `Prepare investor-ready revenue narrative: TAM → SAM → SOM → your ${fmt(annual)} run-rate trajectory.`,
  ];

  return wrapAnalysis(
    section("Executive Summary", execSummary) +
    section("Complete Results Breakdown", resultsTable) +
    section("Deep Dive — What Every Number Means", deepDive) +
    section("Scenario & Sensitivity Analysis", p("How your revenue changes under realistic growth and pricing levers:") + scenarios) +
    section("Risk Flags & Watch Points", risks.length ? `<ul style="margin:4px 0 0 16px;padding:0">${risks.map(bullet).join("")}</ul>` : p("No critical risk flags at current inputs — continue monitoring monthly.")) +
    section("30 / 60 / 90-Day Improvement Roadmap",
      numberedPlan("Next 30 Days — Quick Wins", plan30) +
      numberedPlan("Days 31–60 — Build Momentum", plan60) +
      numberedPlan("Days 61–90 — Scale & Systematise", plan90)
    ) +
    section("Strategic Enhancement Opportunities", `<ul style="margin:4px 0 0 16px;padding:0">
      ${bullet(`Convert one-time buyers to recurring: even moving 20% of customers to a subscription adds predictable ${fmt(monthly * 0.2)}/mo base revenue.`)}
      ${bullet(`Increase units per customer from ${unitsPerCustomer} to ${unitsPerCustomer + 1} — adds ${fmt(customers * price)}/mo with zero new acquisition.`)}
      ${bullet(`Extend lifetime from ${lifetime} to ${lifetime + 6} months — raises LTV from ${fmt(ltvPerCustomer)} to ${fmt(price * monthlyRate * (lifetime + 6))} (+${fmt(price * monthlyRate * 6)} per customer).`)}
      ${bullet(`Test 10% price increase on new customers only — if volume holds, that's +${fmt(monthly * 0.1)}/mo (${fmt(annual * 0.1)}/year).`)}
      ${bullet("Feed these numbers into Costing Model → Break-Even → Funding Model for a complete financial stack.")}
    </ul>`)
  );
}

// ── COSTING MODEL ─────────────────────────────────────────────────────────────

function analyzeCosting(out: Record<string, unknown>, inp: Record<string, unknown>): string {
  const fixed = Number(out.totalFixedCosts) || 0;
  const varPerUnit = Number(out.totalVariableCostPerUnit) || 0;
  const varTotal = Number(out.totalVariableCost) || 0;
  const total = Number(out.totalMonthlyCost) || fixed + varTotal;
  const units = Number(out.unitsSold) || Number(inp.unitsSold) || 0;
  const costPerUnit = units > 0 ? total / units : varPerUnit;
  const fixedPct = total > 0 ? (fixed / total) * 100 : 0;
  const varPct = total > 0 ? (varTotal / total) * 100 : 0;
  const annualCost = total * 12;
  const operatingLeverage = fixed > 0 && varTotal > 0 ? (fixed / varTotal).toFixed(1) : "N/A";

  const fixedLines = [
    { label: "Salaries", val: Number(inp.salaries) || 0 },
    { label: "Office Rent", val: Number(inp.officeRent) || 0 },
    { label: "Utilities", val: Number(inp.utilities) || 0 },
    { label: "Software Subscriptions", val: Number(inp.softwareSubscriptions) || 0 },
    { label: "Administrative Costs", val: Number(inp.administrativeCosts) || 0 },
    { label: "Other Fixed Costs", val: Number(inp.otherFixedCosts) || 0 },
  ];
  const varLines = [
    { label: "Raw Material", val: Number(inp.rawMaterial) || 0 },
    { label: "Packaging", val: Number(inp.packaging) || 0 },
    { label: "Shipping / Logistics", val: Number(inp.shippingLogistics) || 0 },
    { label: "Sales Commission", val: Number(inp.salesCommission) || 0 },
    { label: "Payment Gateway Fees", val: Number(inp.paymentGatewayFees) || 0 },
    { label: "Other Variable Costs", val: Number(inp.otherVariableCosts) || 0 },
  ];
  const allLines = [...fixedLines, ...varLines].filter((l) => l.val > 0).sort((a, b) => b.val - a.val);
  const top3 = allLines.slice(0, 3);
  const top3Pct = total > 0 ? top3.reduce((s, l) => s + l.val, 0) / total * 100 : 0;

  const execSummary = p(`<strong>Executive summary:</strong> Total monthly operating cost is <strong>${fmt(total)}</strong> (${fmt(annualCost)}/year), split <strong>${fixedPct.toFixed(0)}% fixed</strong> (${fmt(fixed)}) and <strong>${varPct.toFixed(0)}% variable</strong> (${fmt(varTotal)}). Variable cost per unit: <strong>${fmt(varPerUnit)}</strong>. At ${units.toLocaleString()} units sold, blended all-in cost is <strong>${fmt(costPerUnit)}/unit</strong>. Operating leverage ratio (fixed/variable): <strong>${operatingLeverage}x</strong>.`);

  const resultsTable = metricTable([
    { label: "Total Fixed Costs", value: fmt(fixed), note: `${fixedPct.toFixed(0)}% of total` },
    { label: "Total Variable Cost / Unit", value: fmt(varPerUnit), note: "Per-unit direct cost" },
    { label: "Total Variable Cost (Month)", value: fmt(varTotal), note: `${varPerUnit} × ${units} units` },
    { label: "Total Monthly Cost", value: fmt(total), note: "Fixed + variable" },
    { label: "Units Sold", value: units.toLocaleString(), note: "Volume assumption" },
    { label: "Blended Cost / Unit", value: fmt(costPerUnit), note: "All-in per unit" },
    { label: "Annual Cost Run-Rate", value: fmt(annualCost), note: "12× monthly" },
    { label: "Fixed Cost / Day", value: fmt(fixed / 30), note: "Daily overhead burn" },
    { label: "Top 3 Costs Share", value: `${top3Pct.toFixed(0)}%`, note: top3.map((t) => t.label).join(", ") },
  ]);

  const fixedBreakdown = fixedLines.filter((l) => l.val > 0).map((l) =>
    bullet(`<strong>${l.label}:</strong> ${fmt(l.val)} (${pct(l.val, fixed)} of fixed, ${pct(l.val, total)} of total)${l.val / fixed > 0.35 ? " ⚠ dominant line" : ""}`)
  ).join("");
  const varBreakdown = varLines.filter((l) => l.val > 0).map((l) =>
    bullet(`<strong>${l.label}:</strong> ${fmt(l.val)}/unit (${pct(l.val, varPerUnit)} of variable cost)`)
  ).join("");

  let deepDive = p(`<strong>Cost structure diagnosis:</strong> ${fixedPct > 60 ? "Fixed-heavy" : varPct > 60 ? "Variable-heavy" : "Balanced"} cost base. Fixed-heavy businesses profit faster above break-even but are vulnerable to revenue drops. Your fixed cost of ${fmt(fixed)}/month must be paid regardless of sales — that's ${fmt(fixed / 30)}/day in overhead.`);

  if (costPerUnit > 0) {
    deepDive += p(`<strong>Pricing floor analysis:</strong> All-in cost/unit = ${fmt(costPerUnit)}. Minimum viable prices: <strong>${fmt(costPerUnit * 1.2)}</strong> (20% margin), <strong>${fmt(costPerUnit * 1.3)}</strong> (30% margin — recommended), <strong>${fmt(costPerUnit * 1.5)}</strong> (50% margin — healthy SaaS/product).`);
  }

  if (Number(fixedPct) > 70) deepDive += callout("warn", "Fixed-Cost Dominance", `${fixedPct.toFixed(0)}% of costs are fixed. A 20% revenue drop doesn't reduce costs proportionally — you need strong cash reserves or rapid variable-cost flexibility.`);
  if (units === 0) deepDive += callout("risk", "Missing Volume", "Units sold is zero — variable costs aren't scaling. Link Revenue Model or enter units to get accurate total cost.");

  const scenarios = scenarioTable(
    ["Scenario", "Monthly Cost", "Cost/Unit", "Annual Cost", "Savings"],
    [
      ["Current", fmt(total), fmt(costPerUnit), fmt(annualCost), "—"],
      ["−10% Fixed Costs", fmt(fixed * 0.9 + varTotal), fmt(units > 0 ? (fixed * 0.9 + varTotal) / units : varPerUnit), fmt((fixed * 0.9 + varTotal) * 12), fmt(fixed * 0.1)],
      ["−5% Variable/Unit", fmt(fixed + varPerUnit * 0.95 * units), fmt(units > 0 ? (fixed + varPerUnit * 0.95 * units) / units : varPerUnit * 0.95), fmt((fixed + varPerUnit * 0.95 * units) * 12), fmt(varPerUnit * 0.05 * units)],
      ["+25% Volume", fmt(fixed + varPerUnit * units * 1.25), fmt(units > 0 ? (fixed + varPerUnit * units * 1.25) / (units * 1.25) : varPerUnit), fmt((fixed + varPerUnit * units * 1.25) * 12), `Cost/unit ↓`],
      ["Fixed −10% & Var −5%", fmt(fixed * 0.9 + varPerUnit * 0.95 * units), fmt(units > 0 ? (fixed * 0.9 + varPerUnit * 0.95 * units) / units : 0), fmt((fixed * 0.9 + varPerUnit * 0.95 * units) * 12), fmt(fixed * 0.1 + varPerUnit * 0.05 * units)],
    ]
  );

  const plan30 = [
    `Audit top 3 cost drivers (${top3.map((t) => t.label).join(", ")}) — target 5–10% reduction on each.`,
    "Categorise every expense as fixed or variable — anything misclassified distorts break-even.",
    `Calculate break-even: Fixed (${fmt(fixed)}) ÷ Contribution margin per unit = minimum units needed.`,
    "Negotiate one vendor contract (rent, software, or supplier) this month.",
    "Set a monthly cost review meeting — same day each month, 30 minutes, no exceptions.",
  ];
  const plan60 = [
    "Implement expense approval workflow for any spend above ₹5,000 / $100.",
    "Compare actual costs vs budget for each line item — flag variances > 10%.",
    "Evaluate outsourcing vs in-house for largest salary cost line.",
    "Link units sold from Revenue Model for auto-scaling variable costs.",
  ];
  const plan90 = [
    "Build 12-month cost forecast with fixed base + variable scaling at 3 volume scenarios.",
    "Target total cost reduction of 8–12% while maintaining quality.",
    `Feed ${fmt(fixed)} fixed + ${fmt(varPerUnit)}/unit variable into Break-Even Model.`,
  ];

  return wrapAnalysis(
    section("Executive Summary", execSummary) +
    section("Complete Results Breakdown", resultsTable) +
    section("Fixed Cost Line-Item Analysis", fixedBreakdown ? `<ul style="margin:4px 0 0 16px;padding:0">${fixedBreakdown}</ul>` : p("No fixed costs entered.")) +
    section("Variable Cost Line-Item Analysis", varBreakdown ? `<ul style="margin:4px 0 0 16px;padding:0">${varBreakdown}</ul>` : p("No variable costs entered.")) +
    section("Deep Dive — Cost Structure & Pricing Floor", deepDive) +
    section("Scenario & Cost Optimisation Analysis", p("Stress-test your cost base under reduction and volume scenarios:") + scenarios) +
    section("30 / 60 / 90-Day Cost Discipline Roadmap",
      numberedPlan("Next 30 Days", plan30) +
      numberedPlan("Days 31–60", plan60) +
      numberedPlan("Days 61–90", plan90)
    ) +
    section("Strategic Enhancement Opportunities", `<ul style="margin:4px 0 0 16px;padding:0">
      ${allLines.slice(0, 5).map((l) => bullet(`Review <strong>${l.label}</strong> (${fmt(l.val)}) — is this essential, negotiable, or automatable?`)).join("")}
      ${bullet("Shift fixed → variable where possible (contractors vs FTE, usage-based SaaS vs annual plans) to reduce break-even risk.")}
      ${bullet(`At ${fmt(costPerUnit)}/unit all-in cost, any price below ${fmt(costPerUnit * 1.3)} erodes long-term sustainability.`)}
      ${bullet("Connect to Revenue Model for live unit volume → Costing → Break-Even chain.")}
    </ul>`)
  );
}

// ── BREAK-EVEN MODEL ──────────────────────────────────────────────────────────

function analyzeBreakEven(out: Record<string, unknown>, inp: Record<string, unknown>, slug: string): string {
  const price = Number(out.pricePerUnit || inp.pricePerUnit) || 0;
  const varCost = Number(out.variableCostPerUnit || inp.variableCostPerUnit) || 0;
  const fixed = Number(out.fixedCostMonthly || inp.fixedCostMonthly) || 0;
  const contrib = Number(out.contributionPerUnit) || (price - varCost);
  const beUnits = Number(out.breakEvenUnits) || 0;
  const beRev = Number(out.breakEvenRevenue) || 0;
  const projUnits = Number(out.unitsSoldForProjection || inp.unitsSoldForProjection) || 0;
  const revAtUnits = Number(out.revenueAtUnits) || projUnits * price;
  const costAtUnits = Number(out.totalCostAtUnits) || fixed + projUnits * varCost;
  const profit = Number(out.profitAtUnits) ?? (revAtUnits - costAtUnits);
  const status = String(out.status || (profit >= 0 ? "GREEN" : "RED"));
  const marginPct = price > 0 ? (contrib / price) * 100 : 0;
  const varMarginPct = price > 0 ? (varCost / price) * 100 : 0;
  const marginOfSafety = beUnits > 0 && projUnits > 0 ? ((projUnits - beUnits) / beUnits) * 100 : null;
  const annualProfit = profit * 12;
  const annualRevAtProj = revAtUnits * 12;
  const operatingLeverage = contrib > 0 && projUnits > beUnits ? ((projUnits - beUnits) * contrib * 0.1 / (profit || 1)).toFixed(1) : "N/A";
  const daysToBE = beUnits > 0 && projUnits > 0 && projUnits < beUnits ? Math.ceil((beUnits - projUnits) / Math.max(projUnits / 30, 1)) : null;

  const execSummary = p(`<strong>Executive summary:</strong> Break-even requires <strong>${beUnits.toLocaleString()} units</strong> (${fmt(beRev)}/month). At <strong>${projUnits.toLocaleString()} projected units</strong>, you ${profit >= 0 ? `earn <strong>${fmt(profit)}/month</strong> (${fmt(annualProfit)}/year)` : `lose <strong>${fmt(Math.abs(profit))}/month</strong>`}. Contribution margin: <strong>${fmt(contrib)}/unit (${marginPct.toFixed(1)}%)</strong>. Status: <strong>${status === "GREEN" ? "Profitable ✓" : "Below break-even ✗"}</strong>.`);

  const resultsTable = metricTable([
    { label: "Price Per Unit", value: fmt(price), note: "Revenue lever" },
    { label: "Variable Cost / Unit", value: fmt(varCost), note: `${varMarginPct.toFixed(1)}% of price` },
    { label: "Fixed Cost (Monthly)", value: fmt(fixed), note: `${fmt(fixed * 12)}/year` },
    { label: "Contribution / Unit", value: fmt(contrib), note: `${marginPct.toFixed(1)}% margin` },
    { label: "Break-Even Units", value: beUnits.toLocaleString(), note: "Minimum volume" },
    { label: "Break-Even Revenue", value: fmt(beRev), note: "Minimum revenue" },
    { label: "Projected Units", value: projUnits.toLocaleString(), note: "Your plan" },
    { label: "Revenue at Projection", value: fmt(revAtUnits), note: `${fmt(annualRevAtProj)}/year` },
    { label: "Total Cost at Projection", value: fmt(costAtUnits), note: "Fixed + variable" },
    { label: "Profit / Loss at Projection", value: fmt(profit), note: `${fmt(annualProfit)}/year` },
    { label: "Margin of Safety", value: marginOfSafety != null ? `${marginOfSafety.toFixed(0)}%` : "—", note: marginOfSafety != null && marginOfSafety >= 0 ? "Above BE" : "Below BE" },
    { label: "Operating Leverage", value: String(operatingLeverage), note: "Profit sensitivity" },
  ]);

  let deepDive = p(`<strong>Break-even mechanics:</strong> Fixed costs (${fmt(fixed)}/mo) must be covered by contribution from each sale. Each unit contributes ${fmt(contrib)} after paying ${fmt(varCost)} variable cost from ${fmt(price)} price. You need ${beUnits.toLocaleString()} such contributions to break even.`);

  if (contrib <= 0) {
    deepDive += callout("risk", "Negative Contribution — Business Model Broken", `Price (${fmt(price)}) ≤ Variable cost (${fmt(varCost)}). Every sale loses money before fixed costs. Fix: raise price to at least ${fmt(varCost * 1.1)} or cut variable cost below ${fmt(price * 0.7)}.`);
  } else if (marginPct < 20) {
    deepDive += callout("warn", "Thin Contribution Margin", `${marginPct.toFixed(1)}% contribution margin leaves little room for error. Industry target: 30–50%+.`);
  } else if (marginPct >= 40) {
    deepDive += callout("ok", "Strong Contribution Margin", `${marginPct.toFixed(1)}% gives healthy cushion above variable costs — good foundation for profitability.`);
  }

  if (profit > 0 && marginOfSafety != null) {
    deepDive += p(`<strong>Profitability analysis:</strong> You are ${marginOfSafety.toFixed(0)}% above break-even. Sales can drop by ${Math.floor(projUnits - beUnits).toLocaleString()} units before you hit loss-making territory. Monthly profit of ${fmt(profit)} scales linearly — every additional unit adds ${fmt(contrib)}.`);
  } else if (profit < 0) {
    const gap = Math.abs(profit);
    const unitsNeeded = contrib > 0 ? Math.ceil(gap / contrib) : 0;
    deepDive += p(`<strong>Gap analysis:</strong> You need ${unitsNeeded.toLocaleString()} more units/month OR ${fmt(gap)} in combined price increase / cost reduction to reach break-even.${daysToBE ? ` At current growth rate, ~${daysToBE} days to close the gap if volume increases linearly.` : ""}`);
  }

  const leverRows: string[][] = [["Current", beUnits.toLocaleString(), fmt(beRev), fmt(profit)]];
  if (contrib > 0) {
    leverRows.push(["Fixed −10%", Math.ceil(fixed * 0.9 / contrib).toLocaleString(), fmt(Math.ceil(fixed * 0.9 / contrib) * price), fmt(projUnits * contrib - fixed * 0.9)]);
    leverRows.push(["Price +5%", Math.ceil(fixed / (price * 1.05 - varCost)).toLocaleString(), fmt(Math.ceil(fixed / (price * 1.05 - varCost)) * price * 1.05), fmt(projUnits * (price * 1.05 - varCost) - fixed)]);
    leverRows.push(["Var cost −5%", Math.ceil(fixed / (contrib + varCost * 0.05)).toLocaleString(), fmt(Math.ceil(fixed / (contrib + varCost * 0.05)) * price), fmt(projUnits * (contrib + varCost * 0.05) - fixed)]);
    leverRows.push(["Units +20%", beUnits.toLocaleString(), fmt(beRev), fmt((projUnits * 1.2 * price) - (fixed + projUnits * 1.2 * varCost))]);
  }
  const scenarios = scenarioTable(["Lever", "BE Units", "BE Revenue", "Profit at Proj"], leverRows);

  const proj = out.projection as { units: number; revenue: number; totalCost: number; profit: number }[] | undefined;
  let projAnalysis = "";
  if (Array.isArray(proj) && proj.length > 0) {
    const turnProfit = proj.find((r) => r.profit >= 0);
    projAnalysis = p(`<strong>Projection table insight:</strong> Profit turns positive at <strong>${turnProfit ? turnProfit.units.toLocaleString() + " units" : "beyond modeled range"}</strong> (${turnProfit ? fmt(turnProfit.revenue) + " revenue" : ""}). Review the full projection table in Results above for volume-profit mapping.`);
  }

  const plan30 = [
    profit < 0 ? `Close the ${fmt(Math.abs(profit))}/mo gap: add ${contrib > 0 ? Math.ceil(Math.abs(profit) / contrib).toLocaleString() : "?"} units OR cut fixed costs by ${fmt(Math.abs(profit))}.` : `Protect ${fmt(profit)}/mo profit — monitor weekly unit sales vs ${beUnits.toLocaleString()} BE threshold.`,
    `Track contribution margin weekly — must stay above ${marginPct.toFixed(0)}%.`,
    "Model best/base/worst unit scenarios (±20%) in this tool monthly.",
    slug === "break-even-pro" ? "Use the projection table to identify exact profit inflection point." : "Upgrade to Break-Even Pro for full projection table.",
  ];
  const plan60 = [
    "Negotiate fixed cost reductions targeting 5–10% (rent, software, admin).",
    "Test 5% price increase on new customers — measure volume impact vs margin gain.",
    "Link Revenue + Costing models so break-even auto-updates with live data.",
  ];
  const plan90 = [
    "Achieve 25%+ margin of safety above break-even for business resilience.",
    "Build monthly P&L dashboard: revenue, variable cost, fixed cost, contribution, profit.",
    "If raising funding, show investors: BE point, current volume, and path to 2× BE volume.",
  ];

  return wrapAnalysis(
    section("Executive Summary", execSummary) +
    section("Complete Results Breakdown", resultsTable) +
    section("Deep Dive — Break-Even & Profitability", deepDive + projAnalysis) +
    section("Lever Analysis — What Moves the Needle", p("How each lever changes break-even and projected profit:") + scenarios) +
    section("30 / 60 / 90-Day Profitability Roadmap",
      numberedPlan("Next 30 Days", plan30) +
      numberedPlan("Days 31–60", plan60) +
      numberedPlan("Days 61–90", plan90)
    ) +
    section("Strategic Enhancement Opportunities", `<ul style="margin:4px 0 0 16px;padding:0">
      ${contrib > 0 && fixed > 0 ? bullet(`Cutting fixed costs 10% (${fmt(fixed * 0.1)}) drops break-even by ~${Math.ceil(fixed * 0.1 / contrib).toLocaleString()} units.`) : ""}
      ${price > 0 ? bullet(`5% price increase → new price ${fmt(price * 1.05)} → break-even drops to ~${contrib > 0 ? Math.ceil(fixed / (price * 1.05 - varCost)).toLocaleString() : "?"} units.`) : ""}
      ${bullet(`Every unit above ${beUnits.toLocaleString()} adds ${fmt(contrib)} pure profit — focus sales efforts on surpassing break-even by 25%+.`)}
      ${bullet("Chain models: Revenue (volume) → Costing (cost/unit) → Break-Even (viability) → Funding (capital need).")}
    </ul>`)
  );
}

// ── KNOW YOUR NUMBERS ─────────────────────────────────────────────────────────

const SECTION_DEEP: Record<string, { why: string; actions: string[] }> = {
  "Cash Flow": {
    why: "Cash is oxygen. Without visibility on cash position, burn rate, and runway, every other metric is theoretical.",
    actions: ["Build 13-week cash flow forecast", "Review bank balance every Monday", "Set minimum cash reserve policy (3–6 months)", "Track burn rate weekly"],
  },
  Revenue: {
    why: "Revenue quality matters as much as quantity — recurring vs one-time, collection speed, and receivables ageing determine real cash.",
    actions: ["Age receivables weekly (0–30, 31–60, 61–90, 90+ days)", "Measure recurring revenue %", "Shorten collection cycle with automated reminders", "Segment revenue by product/customer"],
  },
  Costs: {
    why: "Uncontrolled costs silently kill margins. Fixed/variable separation is prerequisite for break-even and pricing decisions.",
    actions: ["Tag every expense fixed vs variable in accounting software", "Monthly cost review with department heads", "Create 30-day emergency cost reduction plan", "Benchmark top 5 costs against industry"],
  },
  "Unit Economics": {
    why: "Investors fund unit economics, not ideas. Gross margin, CAC, LTV, and LTV/CAC ratio determine if growth creates or destroys value.",
    actions: ["Calculate gross margin % per product line", "Track CAC by channel monthly", "Compute LTV from Revenue Model", "Target LTV/CAC ≥ 3×"],
  },
  Forecasting: {
    why: "Without forecasts, you're driving blind. 12–24 month models with scenarios separate professional operators from hobbyists.",
    actions: ["Build 12-month rolling forecast in FinMech", "Update assumptions monthly", "Model best/base/worst cases", "Set break-even as monthly KPI"],
  },
  Compliance: {
    why: "Tax surprises and outdated books destroy credibility with investors, banks, and auditors. Compliance is non-negotiable.",
    actions: ["Calendar all GST/TDS/IT deadlines", "Monthly bookkeeping close by 10th", "Set aside 25–30% of profit for tax provisions", "Engage qualified CA/CFO"],
  },
  Fundraising: {
    why: "Messy cap tables and unclear use-of-funds kill deals. Investors expect clean structure and dilution literacy.",
    actions: ["Update cap table in FinMech Cap Table model", "Model next round dilution scenarios", "Prepare use-of-funds breakdown", "Draft 12-slide financial appendix for pitch deck"],
  },
  Controls: {
    why: "Mixed personal/business finances and missing approvals are fraud and audit risks that scale with team size.",
    actions: ["Separate business bank account today if not done", "Implement expense approval for >₹5K/$100", "Monthly bank reconciliation", "Build KPI dashboard (revenue, burn, runway, margin)"],
  },
};

function analyzeKnowYourNumbers(out: Record<string, unknown>, inp: Record<string, unknown>): string {
  const score = Number(out.totalScore) || 0;
  const max = Number(out.maxPossible) || 0;
  const pct = Number(out.readinessPercentage) || 0;
  const status = String(out.readinessStatus || "");
  const advisory = String(out.advisorySummary || "");
  const sections = out.sectionScores as { section: string; score: number; maxPossible: number; percentage: number }[] | undefined;
  const answers = inp as Record<string, ChecklistResponse>;

  const weak = (sections || []).filter((s) => s.percentage < 50).sort((a, b) => a.percentage - b.percentage);
  const partial = (sections || []).filter((s) => s.percentage >= 50 && s.percentage < 80);
  const strong = (sections || []).filter((s) => s.percentage >= 80).sort((a, b) => b.percentage - a.percentage);

  const execSummary = p(`<strong>Executive summary:</strong> Financial readiness score: <strong>${pct.toFixed(0)}%</strong> (${score}/${max} weighted points). Status: <strong>${status}</strong>. ${advisory} ${weak.length} critical gap${weak.length !== 1 ? "s" : ""}, ${partial.length} partial area${partial.length !== 1 ? "s" : ""}, ${strong.length} strength${strong.length !== 1 ? "s" : ""} identified across 8 categories.`);

  const resultsTable = metricTable([
    { label: "Overall Readiness", value: `${pct.toFixed(1)}%`, note: status },
    { label: "Weighted Score", value: `${score} / ${max}`, note: "Yes=2, Partial=1, No=0" },
    { label: "Critical Gaps (<50%)", value: String(weak.length), note: weak.map((s) => s.section).join(", ") || "None" },
    { label: "Partial Areas (50–79%)", value: String(partial.length), note: partial.map((s) => s.section).join(", ") || "None" },
    { label: "Strengths (≥80%)", value: String(strong.length), note: strong.map((s) => s.section).join(", ") || "None" },
    { label: "Questions Assessed", value: String(Object.keys(answers).length), note: `${QUESTIONS.length} total` },
  ]);

  let sectionDeepDive = "";
  (sections || []).forEach((s) => {
    const icon = s.percentage >= 80 ? "✓" : s.percentage >= 50 ? "◐" : "✗";
    const color = s.percentage >= 80 ? "#16a34a" : s.percentage >= 50 ? "#d97706" : "#dc2626";
    const meta = SECTION_DEEP[s.section];
    const sectionQs = QUESTIONS.filter((q) => q.section === s.section);
    const qDetail = sectionQs.map((q) => {
      const ans = answers[q.id] || "Unanswered";
      const ansColor = ans === "Yes" ? "#16a34a" : ans === "Partial" ? "#d97706" : "#dc2626";
      return `<tr><td style="padding:5px 8px;border-bottom:1px solid #eee;font-size:11px">${q.text}</td>
        <td style="padding:5px 8px;border-bottom:1px solid #eee;text-align:center;font-weight:700;color:${ansColor};font-size:11px">${ans}</td>
        <td style="padding:5px 8px;border-bottom:1px solid #eee;text-align:center;font-size:11px;color:#888">wt ${q.weight}</td></tr>`;
    }).join("");

    sectionDeepDive += `<div style="margin:12px 0;padding:12px;border:1px solid #eee;border-radius:8px">
      <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:6px">
        <span style="font-weight:700;color:${color}">${icon} ${s.section}</span>
        <span style="font-size:12px;font-weight:700">${s.score}/${s.maxPossible} (${s.percentage.toFixed(0)}%)</span>
      </div>
      ${meta ? p(`<em>${meta.why}</em>`) : ""}
      <table style="width:100%;border-collapse:collapse;margin:6px 0">
        <thead><tr style="background:#f5f5f5"><th style="padding:5px 8px;text-align:left;font-size:10px">Question</th><th style="padding:5px 8px;font-size:10px">Answer</th><th style="padding:5px 8px;font-size:10px">Wt</th></tr></thead>
        <tbody>${qDetail}</tbody>
      </table>
      ${meta ? `<ul style="margin:4px 0 0 16px;padding:0">${meta.actions.map(bullet).join("")}</ul>` : ""}
    </div>`;
  });

  let statusCallout = "";
  if (pct >= 80) statusCallout = callout("ok", "FINANCE-READY", "You demonstrate institutional-grade financial discipline. Focus on optimisation, investor reporting, and scaling systems. You're ready for due diligence conversations.");
  else if (pct >= 50) statusCallout = callout("warn", "GROWTH RISK", "Foundational gaps could stall growth or fundraising. Fix weak sections within 60 days. Investors will probe your weakest area — prepare answers now.");
  else statusCallout = callout("risk", "SURVIVAL RISK", "Critical financial blind spots exist. Do NOT scale spend or raise capital until cash visibility, cost control, and compliance basics are fixed. This is urgent.");

  const plan30 = weak.slice(0, 2).flatMap((s) => (SECTION_DEEP[s.section]?.actions.slice(0, 2) || [`Fix ${s.section} gaps`])).concat([
    "Re-run this checklist in 30 days — target +10 percentage points overall.",
    "Share results with co-founder/CFO — assign one owner per weak section.",
  ]);
  const plan60 = partial.slice(0, 2).flatMap((s) => (SECTION_DEEP[s.section]?.actions.slice(2, 4) || [])).concat([
    "Complete all 'Partial' answers to 'Yes' — document evidence for each.",
    "Build monthly financial dashboard with top 5 KPIs.",
  ]);
  const plan90 = [
    "Target 80%+ readiness score — re-assess all 25 questions.",
    "Prepare investor data room: forecasts, cap table, unit economics, compliance calendar.",
    "Schedule quarterly checklist reviews — financial maturity is a process, not an event.",
    strong.length > 0 ? `Leverage ${strong.map((s) => s.section).join(", ")} strengths in pitch narrative.` : "Build at least 3 sections to 80%+ strength.",
  ];

  return wrapAnalysis(
    section("Executive Summary", execSummary + statusCallout) +
    section("Complete Results Breakdown", resultsTable) +
    section("Category-by-Category Deep Dive", sectionDeepDive) +
    section("30 / 60 / 90-Day Readiness Roadmap",
      numberedPlan("Next 30 Days — Fix Critical Gaps", plan30.slice(0, 6)) +
      numberedPlan("Days 31–60 — Strengthen Partial Areas", plan60.slice(0, 5)) +
      numberedPlan("Days 61–90 — Investor-Grade Maturity", plan90)
    ) +
    section("Strategic Enhancement Opportunities", `<ul style="margin:4px 0 0 16px;padding:0">
      ${weak.length > 0 ? bullet(`<strong>Priority 1:</strong> ${weak.map((s) => `${s.section} (${s.percentage.toFixed(0)}%)`).join(", ")} — these weighted categories drag your score most.`) : bullet("No critical gaps — maintain discipline and push partial areas to 'Yes'.")}
      ${bullet("Cash Flow (weight 3) and Unit Economics (weight 3) have highest impact — even one 'No' here significantly lowers readiness.")}
      ${bullet("Use FinMech models to convert 'No' answers into 'Yes': Revenue Model (LTV), Costing (margins), Break-Even (viability), Cap Table (fundraising).")}
      ${bullet(`Moving from ${pct.toFixed(0)}% to 80% requires fixing ~${Math.ceil((0.8 * max - score) / 6)} weighted question-points — focus highest-weight gaps first.`)}
    </ul>`)
  );
}

// ── Public exports ────────────────────────────────────────────────────────────

export function generateFreeModelAnalysis(calc: CalculationExport): string {
  const slug = calc.modelSlug;
  const out = calc.outputs as Record<string, unknown>;
  const inp = calc.inputs as Record<string, unknown>;

  if (slug === "revenue-model") return analyzeRevenue(out, inp);
  if (slug === "costing-model") return analyzeCosting(out, inp);
  if (slug === "know-your-numbers") return analyzeKnowYourNumbers(out, inp);
  if (slug.includes("break-even")) return analyzeBreakEven(out, inp, slug);
  return "";
}

export function getFreeModelHeroCards(calc: CalculationExport): Row[] {
  const out = calc.outputs as Record<string, unknown>;
  const slug = calc.modelSlug;

  if (slug === "revenue-model") {
    const monthly = Number(out.monthlyRevenue) || 0;
    const customers = Number((calc.inputs as Record<string, unknown>).customersPerMonth) || 0;
    return [
      { label: "Monthly Revenue", value: fmt(out.monthlyRevenue) },
      { label: "Annual Run-Rate", value: fmt(out.annualRevenue) },
      { label: "LTV / Customer", value: fmt(Number(out.pricePerUnit) * Number(out.monthlyPurchaseRate) * Number(out.customerLifetimeMonths)) },
      { label: "ARPU", value: fmt(customers > 0 ? monthly / customers : 0) },
    ];
  }
  if (slug === "costing-model") {
    const total = Number(out.totalMonthlyCost) || 0;
    const units = Number(out.unitsSold) || 0;
    return [
      { label: "Total Monthly Cost", value: fmt(total) },
      { label: "Fixed Costs", value: fmt(out.totalFixedCosts) },
      { label: "Variable / Unit", value: fmt(out.totalVariableCostPerUnit) },
      { label: "Cost / Unit (All-In)", value: fmt(units > 0 ? total / units : out.totalVariableCostPerUnit) },
    ];
  }
  if (slug.includes("break-even")) {
    return [
      { label: "Break-Even Units", value: fmt(out.breakEvenUnits) },
      { label: "Break-Even Revenue", value: fmt(out.breakEvenRevenue) },
      { label: "Contribution / Unit", value: fmt(out.contributionPerUnit) },
      { label: "Monthly Profit", value: fmt(out.profitAtUnits) },
    ];
  }
  if (slug === "know-your-numbers") {
    return [
      { label: "Readiness Score", value: `${Number(out.readinessPercentage || 0).toFixed(0)}%` },
      { label: "Status", value: String(out.readinessStatus || "—") },
      { label: "Score", value: `${out.totalScore}/${out.maxPossible}` },
    ];
  }
  return [];
}

function resultsTableHTML(rows: { label: string; value: string }[], tierColor: string, title?: string) {
  return `${title ? `<p style="font-size:11px;font-weight:700;color:#888;text-transform:uppercase;margin:16px 0 8px">${title}</p>` : ""}
    <table style="width:100%;border-collapse:collapse;font-size:12px">
    ${rows.filter((r) => r.value !== "—" && r.value !== "0" && r.value !== "0.00").map((r, i) => `<tr style="background:${i % 2 === 0 ? "#fafafa" : "#fff"}">
      <td style="padding:8px 12px;border-bottom:1px solid #eee;color:#555;width:45%">${r.label}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #eee;text-align:right;font-weight:700;color:${tierColor}">${r.value}</td>
    </tr>`).join("")}
  </table>`;
}

export function formatFreeModelOutputsHTML(calc: CalculationExport, tierColor: string): string | null {
  const slug = calc.modelSlug;
  const out = calc.outputs as Record<string, unknown>;
  const inp = calc.inputs as Record<string, unknown>;

  if (slug === "know-your-numbers") {
    const sections = out.sectionScores as { section: string; score: number; maxPossible: number; percentage: number }[] | undefined;
    if (!Array.isArray(sections)) return null;
    const answers = inp as Record<string, ChecklistResponse>;
    const statusColor = out.statusColor === "green" ? "#16a34a" : out.statusColor === "amber" ? "#d97706" : "#dc2626";
    const statusBg = out.statusColor === "green" ? "#f0fdf4" : out.statusColor === "amber" ? "#fffbeb" : "#fef2f2";

    const questionRows = QUESTIONS.map((q, i) => {
      const ans = answers[q.id] || "—";
      const ansColor = ans === "Yes" ? "#16a34a" : ans === "Partial" ? "#d97706" : ans === "No" ? "#dc2626" : "#888";
      return `<tr style="background:${i % 2 === 0 ? "#fafafa" : "#fff"}">
        <td style="padding:6px 10px;border-bottom:1px solid #eee;font-size:11px;color:#888">${q.section}</td>
        <td style="padding:6px 10px;border-bottom:1px solid #eee;font-size:11px">${q.text}</td>
        <td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:center;font-weight:700;color:${ansColor}">${ans}</td>
        <td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:center;font-size:11px">${q.weight}</td>
      </tr>`;
    }).join("");

    return `
      <div style="margin-bottom:20px;padding:20px;background:${statusBg};border:1px solid ${statusColor}44;border-radius:12px;text-align:center">
        <div style="font-size:10px;color:#888;text-transform:uppercase;letter-spacing:1px">Overall Financial Readiness</div>
        <div style="font-size:36px;font-weight:900;color:${statusColor}">${Number(out.readinessPercentage || 0).toFixed(0)}%</div>
        <div style="font-size:15px;font-weight:800;color:${statusColor}">${out.readinessStatus}</div>
        <div style="font-size:12px;color:#555;margin-top:10px;line-height:1.5">${out.advisorySummary || ""}</div>
        <div style="font-size:11px;color:#888;margin-top:6px">Weighted Score: ${out.totalScore} / ${out.maxPossible}</div>
      </div>
      <p style="font-size:11px;font-weight:700;color:#888;text-transform:uppercase;margin-bottom:8px">Score by Category</p>
      <table style="width:100%;border-collapse:collapse;font-size:12px;margin-bottom:20px">
        <thead><tr style="background:${tierColor};color:#fff">
          <th style="text-align:left;padding:9px 12px">Category</th>
          <th style="text-align:right;padding:9px 12px">Score</th>
          <th style="text-align:right;padding:9px 12px">Max</th>
          <th style="text-align:right;padding:9px 12px">%</th>
          <th style="text-align:center;padding:9px 12px">Rating</th>
        </tr></thead>
        <tbody>${sections.map((s, i) => {
          const rating = s.percentage >= 80 ? "Strong" : s.percentage >= 50 ? "Partial" : "Gap";
          const rColor = s.percentage >= 80 ? "#16a34a" : s.percentage >= 50 ? "#d97706" : "#dc2626";
          return `<tr style="background:${i % 2 === 0 ? "#fafafa" : "#fff"}">
            <td style="padding:8px 12px;border-bottom:1px solid #eee;font-weight:500">${s.section}</td>
            <td style="padding:8px 12px;border-bottom:1px solid #eee;text-align:right">${s.score}</td>
            <td style="padding:8px 12px;border-bottom:1px solid #eee;text-align:right">${s.maxPossible}</td>
            <td style="padding:8px 12px;border-bottom:1px solid #eee;text-align:right;font-weight:700">${s.percentage.toFixed(0)}%</td>
            <td style="padding:8px 12px;border-bottom:1px solid #eee;text-align:center;color:${rColor};font-weight:700">${rating}</td>
          </tr>`;
        }).join("")}</tbody>
      </table>
      <p style="font-size:11px;font-weight:700;color:#888;text-transform:uppercase;margin-bottom:8px">All 25 Questions &amp; Your Answers</p>
      <table style="width:100%;border-collapse:collapse;font-size:11px">
        <thead><tr style="background:${tierColor};color:#fff">
          <th style="padding:7px 10px;text-align:left">Category</th>
          <th style="padding:7px 10px;text-align:left">Question</th>
          <th style="padding:7px 10px;text-align:center">Answer</th>
          <th style="padding:7px 10px;text-align:center">Weight</th>
        </tr></thead>
        <tbody>${questionRows}</tbody>
      </table>`;
  }

  if (slug.includes("break-even")) {
    const proj = out.projection as { units: number; revenue: number; totalCost: number; profit: number }[] | undefined;
    const marginPct = Number(out.pricePerUnit) > 0 ? ((Number(out.contributionPerUnit) / Number(out.pricePerUnit)) * 100).toFixed(1) : "0";
    let html = resultsTableHTML([
      { label: "Price Per Unit", value: fmt(out.pricePerUnit) },
      { label: "Variable Cost Per Unit", value: fmt(out.variableCostPerUnit) },
      { label: "Fixed Cost (Monthly)", value: fmt(out.fixedCostMonthly) },
      { label: "Contribution Per Unit", value: fmt(out.contributionPerUnit) },
      { label: "Contribution Margin %", value: `${marginPct}%` },
      { label: "Break-Even Units", value: fmt(out.breakEvenUnits) },
      { label: "Break-Even Revenue", value: fmt(out.breakEvenRevenue) },
      { label: "Units Sold (Projection)", value: fmt(out.unitsSoldForProjection) },
      { label: "Revenue at Projection", value: fmt(out.revenueAtUnits) },
      { label: "Total Cost at Projection", value: fmt(out.totalCostAtUnits) },
      { label: "Profit / Loss at Projection", value: fmt(out.profitAtUnits) },
      { label: "Annual Profit (est.)", value: fmt(Number(out.profitAtUnits) * 12) },
      { label: "Status", value: String(out.status || (Number(out.profitAtUnits) >= 0 ? "GREEN" : "RED")) },
    ], tierColor);

    if (Array.isArray(proj) && proj.length > 0) {
      html += `<p style="font-size:11px;font-weight:700;color:#888;text-transform:uppercase;margin:20px 0 8px">Profit / Loss Projection by Volume</p>
        <table style="width:100%;border-collapse:collapse;font-size:11px">
          <thead><tr style="background:${tierColor};color:#fff">
            <th style="padding:7px 10px;text-align:right">Units</th>
            <th style="padding:7px 10px;text-align:right">Revenue</th>
            <th style="padding:7px 10px;text-align:right">Total Cost</th>
            <th style="padding:7px 10px;text-align:right">Profit / Loss</th>
            <th style="padding:7px 10px;text-align:center">Status</th>
          </tr></thead>
          <tbody>${proj.map((row, i) => `<tr style="background:${i % 2 === 0 ? "#fafafa" : "#fff"}">
            <td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:right">${row.units.toLocaleString()}</td>
            <td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:right">${fmt(row.revenue)}</td>
            <td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:right">${fmt(row.totalCost)}</td>
            <td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:right;font-weight:700;color:${row.profit >= 0 ? "#16a34a" : "#dc2626"}">${fmt(row.profit)}</td>
            <td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:center;font-weight:700;color:${row.profit >= 0 ? "#16a34a" : "#dc2626"}">${row.profit >= 0 ? "PROFIT" : "LOSS"}</td>
          </tr>`).join("")}</tbody>
        </table>`;
    }
    return html;
  }

  if (slug === "revenue-model") {
    const price = Number(out.pricePerUnit) || 0;
    const customers = Number(inp.customersPerMonth) || 0;
    const lifetime = Number(out.customerLifetimeMonths) || 0;
    const monthlyRate = Number(out.monthlyPurchaseRate) || 0;
    const ltv = price * monthlyRate * lifetime;
    return (
      resultsTableHTML([
        { label: "Customers Per Month", value: String(customers) },
        { label: "Units Per Customer", value: String(inp.unitsPerCustomer ?? "—") },
        { label: "Purchase Frequency / Year", value: String(inp.purchaseFrequencyPerYear ?? "—") },
        { label: "Customer Lifetime (Months)", value: String(lifetime) },
      ], tierColor, "Inputs") +
      resultsTableHTML([
        { label: "Price Per Unit", value: fmt(out.pricePerUnit) },
        { label: "Monthly Purchase Rate", value: String(out.monthlyPurchaseRate ?? "—") },
        { label: "Monthly Units Sold", value: fmt(out.monthlyUnitsSold) },
        { label: "Monthly Revenue", value: fmt(out.monthlyRevenue) },
        { label: "Quarterly Revenue (est.)", value: fmt(Number(out.monthlyRevenue) * 3) },
        { label: "Annual Revenue Run-Rate", value: fmt(out.annualRevenue) },
        { label: "ARPU (Rev / Customer)", value: fmt(customers > 0 ? Number(out.monthlyRevenue) / customers : 0) },
        { label: "LTV Per Customer", value: fmt(ltv) },
        { label: "Max Affordable CAC (LTV ÷ 3)", value: fmt(ltv / 3) },
      ], tierColor, "Calculated Results")
    );
  }

  if (slug === "costing-model") {
    const fixed = Number(out.totalFixedCosts) || 0;
    const total = Number(out.totalMonthlyCost) || 0;
    const units = Number(out.unitsSold) || 0;
    return (
      resultsTableHTML([
        { label: "Salaries", value: fmt(inp.salaries) },
        { label: "Office Rent", value: fmt(inp.officeRent) },
        { label: "Utilities", value: fmt(inp.utilities) },
        { label: "Software Subscriptions", value: fmt(inp.softwareSubscriptions) },
        { label: "Administrative Costs", value: fmt(inp.administrativeCosts) },
        { label: "Other Fixed Costs", value: fmt(inp.otherFixedCosts) },
      ], tierColor, "Fixed Cost Inputs") +
      resultsTableHTML([
        { label: "Raw Material / Unit", value: fmt(inp.rawMaterial) },
        { label: "Packaging / Unit", value: fmt(inp.packaging) },
        { label: "Shipping / Unit", value: fmt(inp.shippingLogistics) },
        { label: "Sales Commission / Unit", value: fmt(inp.salesCommission) },
        { label: "Payment Gateway / Unit", value: fmt(inp.paymentGatewayFees) },
        { label: "Other Variable / Unit", value: fmt(inp.otherVariableCosts) },
      ], tierColor, "Variable Cost Inputs (Per Unit)") +
      resultsTableHTML([
        { label: "Total Fixed Costs", value: fmt(fixed) },
        { label: "Total Variable Cost / Unit", value: fmt(out.totalVariableCostPerUnit) },
        { label: "Total Variable Cost", value: fmt(out.totalVariableCost) },
        { label: "Total Monthly Cost", value: fmt(total) },
        { label: "Units Sold", value: fmt(units) },
        { label: "Blended Cost / Unit", value: fmt(units > 0 ? total / units : out.totalVariableCostPerUnit) },
        { label: "Fixed Cost / Day", value: fmt(fixed / 30) },
        { label: "Annual Cost Run-Rate", value: fmt(total * 12) },
        { label: "Pricing Floor (30% margin)", value: fmt((units > 0 ? total / units : Number(out.totalVariableCostPerUnit)) * 1.3) },
      ], tierColor, "Calculated Results")
    );
  }

  return null;
}
