export interface ModelField {
  key: string;
  label: string;
  type: "currency" | "number" | "percent" | "text";
  placeholder: string;
}

export interface FinModel {
  slug: string;
  name: string;
  description: string;
  tier: "free" | "standalone" | "standard" | "investor";
  category: string;
  icon: string;
  linkedModels?: string[];
  fields: ModelField[];
  customPage?: boolean;
}

export const MODELS: Record<string, FinModel> = {
  "revenue-model": {
    slug: "revenue-model",
    name: "Revenue Model",
    description: "Monthly & annual revenue from customers, units, and pricing — feeds into Costing & Break-even.",
    tier: "free",
    category: "Revenue",
    icon: "DollarSign",
    customPage: true,
    fields: [],
  },
  "costing-model": {
    slug: "costing-model",
    name: "Costing Model",
    description: "Fixed + variable cost breakdown — receives units from Revenue, feeds costs to Break-even.",
    tier: "free",
    category: "Costing",
    icon: "Calculator",
    customPage: true,
    fields: [],
  },
  "break-even-basic": {
    slug: "break-even-basic",
    name: "Break-even Calculator",
    description: "Contribution margin, break-even units & revenue with projection — receives data from Revenue + Costing.",
    tier: "free",
    category: "Profitability",
    icon: "TrendingUp",
    customPage: true,
    fields: [],
  },
  "know-your-numbers": {
    slug: "know-your-numbers",
    name: "Know Your Business Numbers",
    description: "25-question checklist across 8 categories — weighted scoring with readiness status & advisory.",
    tier: "free",
    category: "Overview",
    icon: "BarChart3",
    customPage: true,
    fields: [],
  },
  "income-statement": {
    slug: "income-statement",
    name: "Income Statement",
    description: "Full P&L model — month-by-month input with automatic quarterly & annual roll-ups. Exact Excel match with EBITDA, EBIT, PBT, PAT, margins, and status analysis.",
    tier: "standalone",
    category: "Financial Statements",
    icon: "FileText",
    linkedModels: ["balance-sheet", "cash-flow-statement"],
    customPage: true,
    fields: [],
  },
  "balance-sheet": {
    slug: "balance-sheet",
    name: "Balance Sheet",
    description: "Full balance sheet — Non-Current & Current Assets, Equity, Liabilities with balance check, working capital, Current/Quick/Debt-Equity/Proprietary ratios.",
    tier: "standalone",
    category: "Financial Statements",
    icon: "Scale",
    linkedModels: ["income-statement", "cash-flow-statement"],
    customPage: true,
    fields: [],
  },
  "burn-runway": {
    slug: "burn-runway",
    name: "Burn & Runway Monitor",
    description: "Month-by-month burn tracking with cumulative cash, gross/net burn, runway, ratios & GREEN/AMBER/RED classification.",
    tier: "standalone",
    category: "Cash Management",
    icon: "Flame",
    customPage: true,
    fields: [],
  },
  "cash-flow-statement": {
    slug: "cash-flow-statement",
    name: "Cash Flow Statement",
    description: "Full CFS — CFO, CFI, CFF with Net Cash Flow, Ending Cash, quarterly & annual roll-ups, CFO/PAT & CFO/EBITDA ratios.",
    tier: "standalone",
    category: "Financial Statements",
    icon: "ArrowRightLeft",
    linkedModels: ["income-statement", "balance-sheet"],
    customPage: true,
    fields: [],
  },
  "break-even-pro": {
    slug: "break-even-pro",
    name: "Break-Even Model",
    description: "Contribution per unit, break-even units & revenue with full projection table — exact Excel match.",
    tier: "standalone",
    category: "Profitability",
    icon: "TrendingUp",
    customPage: true,
    fields: [],
  },
  "viability-dashboard": {
    slug: "viability-dashboard",
    name: "Business Viability Dashboard Pro",
    description: "4-input dashboard — Contribution, Margins, Break-even, Margin of Safety with RAG classification & mentoring tips.",
    tier: "standalone",
    category: "Overview",
    icon: "Activity",
    customPage: true,
    fields: [],
  },
  "unit-economics": {
    slug: "unit-economics",
    name: "Unit Economics",
    description: "Month-by-month CAC, LTV, ARPU, Payback Period, Churn & Growth Rate with RAG classification.",
    tier: "standalone",
    category: "Growth",
    icon: "Users",
    customPage: true,
    fields: [],
  },
  "pitchdeck-kpis": {
    slug: "pitchdeck-kpis",
    name: "Pitch Deck KPIs",
    description: "Investor-ready KPIs — Gross Margin, CAC, LTV, Runway, Burn Multiple with RAG classification & summary flags.",
    tier: "standalone",
    category: "Fundraising",
    icon: "Presentation",
    customPage: true,
    fields: [],
  },
  "dcf-valuation": {
    slug: "dcf-valuation",
    name: "DCF Valuation Model",
    description: "Full WACC + 5-year FCFF projection + Terminal Value + Enterprise & Equity Value — exact Excel match.",
    tier: "standalone",
    category: "Valuation",
    icon: "Gem",
    customPage: true,
    fields: [],
  },
  "funding-model": {
    slug: "funding-model",
    name: "Funding Model",
    description: "Month-by-month cash flow → Working Capital → Net Cash → Max Deficit → Funding Required + Contingency.",
    tier: "standalone",
    category: "Fundraising",
    icon: "Rocket",
    customPage: true,
    fields: [],
  },
  "cap-table": {
    slug: "cap-table",
    name: "Cap Table Mechanics",
    description: "Initial cap table → Funding rounds → Dilution → Exit waterfall + payouts & multiples.",
    tier: "standalone",
    category: "Fundraising",
    icon: "PieChart",
    customPage: true,
    fields: [],
  },
  "std-common-utility": {
    slug: "std-common-utility",
    name: "Common Utility",
    description: "Central Income Statement hub — feeds revenue, costs & margins into all other Standard models.",
    tier: "standard",
    category: "Core",
    icon: "Settings",
    linkedModels: ["std-break-even", "std-burn-runway", "std-unit-economics", "std-movements", "std-cap-table", "std-business-snapshot"],
    customPage: true,
    fields: [],
  },
  "std-break-even": {
    slug: "std-break-even",
    name: "Break-even Model",
    description: "Contribution margin, break-even units & revenue with projection — receives fixed costs from Common Utility.",
    tier: "standard",
    category: "Profitability",
    icon: "TrendingUp",
    linkedModels: ["std-common-utility", "std-burn-runway", "std-business-snapshot"],
    customPage: true,
    fields: [],
  },
  "std-burn-runway": {
    slug: "std-burn-runway",
    name: "Burn & Runway Monitor",
    description: "Month-by-month burn tracking with cumulative cash & runway — receives revenue & costs from Common Utility.",
    tier: "standard",
    category: "Cash Management",
    icon: "Flame",
    linkedModels: ["std-common-utility"],
    customPage: true,
    fields: [],
  },
  "std-unit-economics": {
    slug: "std-unit-economics",
    name: "Unit Economics Basic",
    description: "Month-by-month CAC, LTV, ARPU, Payback, Churn & Growth Rate — receives revenue from Common Utility.",
    tier: "standard",
    category: "Growth",
    icon: "Users",
    linkedModels: ["std-common-utility"],
    customPage: true,
    fields: [],
  },
  "std-cap-table": {
    slug: "std-cap-table",
    name: "Cap Table Mechanics",
    description: "Shareholders, funding rounds, dilution & exit waterfall — integrated with Common Utility.",
    tier: "standard",
    category: "Fundraising",
    icon: "PieChart",
    linkedModels: ["std-common-utility"],
    customPage: true,
    fields: [],
  },
  "std-business-snapshot": {
    slug: "std-business-snapshot",
    name: "Business Snapshot",
    description: "One-page business health overview with RAG scoring — aggregates all Standard models.",
    tier: "standard",
    category: "Overview",
    icon: "LayoutDashboard",
    linkedModels: ["std-common-utility", "std-break-even", "std-burn-runway", "std-unit-economics", "std-movements"],
    customPage: true,
    fields: [],
  },
  "std-movements": {
    slug: "std-movements",
    name: "Working Capital Movements",
    description: "Month-by-month Receivables, Inventory & Payables tracking with Working Capital, CFO, FCF & Cash Conversion Cycle.",
    tier: "standard",
    category: "Cash Management",
    icon: "ArrowRightLeft",
    linkedModels: ["std-common-utility", "std-business-snapshot"],
    customPage: true,
    fields: [],
  },
  "inv-common-utility": {
    slug: "inv-common-utility",
    name: "Common Utility",
    description: "Central Income Statement hub — feeds data into all other Investor Grade models.",
    tier: "investor",
    category: "Core",
    icon: "Settings",
    linkedModels: ["inv-break-even", "inv-burn-runway", "inv-unit-economics", "inv-movements", "inv-dcf-valuation", "inv-funding-model", "inv-cap-table", "inv-business-snapshot"],
    customPage: true,
    fields: [],
  },
  "inv-break-even": {
    slug: "inv-break-even",
    name: "Break-even Model",
    description: "Investor-grade break-even with multi-scenario analysis and projection tables.",
    tier: "investor",
    category: "Profitability",
    icon: "TrendingUp",
    linkedModels: ["inv-common-utility", "inv-business-snapshot"],
    customPage: true,
    fields: [],
  },
  "inv-burn-runway": {
    slug: "inv-burn-runway",
    name: "Burn & Runway Monitor",
    description: "Month-by-month burn tracking with cumulative cash, runway, and RAG classification.",
    tier: "investor",
    category: "Cash Management",
    icon: "Flame",
    linkedModels: ["inv-common-utility"],
    customPage: true,
    fields: [],
  },
  "inv-unit-economics": {
    slug: "inv-unit-economics",
    name: "Unit Economics — Advanced",
    description: "Advanced unit economics with CAC, LTV, churn, cohort analysis, and RAG status.",
    tier: "investor",
    category: "Growth",
    icon: "Users",
    linkedModels: ["inv-common-utility"],
    customPage: true,
    fields: [],
  },
  "inv-funding-model": {
    slug: "inv-funding-model",
    name: "Funding Model",
    description: "Month-by-month cash flow, working capital, and funding requirements with contingency.",
    tier: "investor",
    category: "Fundraising",
    icon: "Rocket",
    linkedModels: ["inv-common-utility", "inv-cap-table", "inv-dcf-valuation"],
    customPage: true,
    fields: [],
  },
  "inv-cap-table": {
    slug: "inv-cap-table",
    name: "Cap Table Mechanics",
    description: "Full cap table with multiple rounds, dilution waterfall, and exit payout analysis.",
    tier: "investor",
    category: "Fundraising",
    icon: "PieChart",
    linkedModels: ["inv-common-utility", "inv-funding-model"],
    customPage: true,
    fields: [],
  },
  "inv-dcf-valuation": {
    slug: "inv-dcf-valuation",
    name: "DCF Valuation Model",
    description: "Full DCF with WACC decomposition, 5-year projection, terminal value, and EV/equity.",
    tier: "investor",
    category: "Valuation",
    icon: "Gem",
    linkedModels: ["inv-common-utility", "inv-funding-model"],
    customPage: true,
    fields: [],
  },
  "inv-movements": {
    slug: "inv-movements",
    name: "Working Capital Movements",
    description: "Month-by-month Receivables, Inventory & Payables tracking with Working Capital, CFO, FCF & Cash Conversion Cycle.",
    tier: "investor",
    category: "Cash Management",
    icon: "ArrowRightLeft",
    linkedModels: ["inv-common-utility", "inv-business-snapshot", "inv-funding-model"],
    customPage: true,
    fields: [],
  },
  "inv-business-snapshot": {
    slug: "inv-business-snapshot",
    name: "Business Snapshot",
    description: "Comprehensive investor-ready overview aggregating all models with health scoring.",
    tier: "investor",
    category: "Overview",
    icon: "LayoutDashboard",
    linkedModels: ["inv-common-utility", "inv-break-even", "inv-burn-runway", "inv-unit-economics", "inv-movements", "inv-dcf-valuation"],
    customPage: true,
    fields: [],
  },
};

export const TIER_INFO: Record<string, { name: string; color: string; bgColor: string }> = {
  free: { name: "Free", color: "text-success", bgColor: "bg-success/10" },
  standalone: { name: "Standalone", color: "text-blue-400", bgColor: "bg-blue-400/10" },
  standard: { name: "Standard", color: "text-primary", bgColor: "bg-primary/10" },
  investor: { name: "Investor Grade", color: "text-amber-400", bgColor: "bg-amber-400/10" },
};
